kind: service
schema: 1

lifecycle: static
version: 2.0.0

build:
  ignore:
    - README.md
  outputDir: ./

deploy:
  prod:
    ref: branch/master
    domains:
      - joshuacole.me
      - www.joshuacole.me
      - thecole.co.uk
      - www.thecole.co.uk
